import { ArrowRight, Check, ChevronDown, CircleAlert, Clock3, Droplets, Filter, Menu, Phone, Search, ShieldCheck, Waves, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Topic = {
  id: string;
  number: string;
  kicker: string;
  title: string;
  intro: string;
  facts: string[];
  takeaway: string;
  tags: string[];
};

const topics: Topic[] = [
  { id: "hard-water", number: "01", kicker: "Water chemistry", title: "High calcium hardness: why Inland Empire tile scales", intro: "Riverside heat turns hard fill water into a mineral trap. As 1.5–2 inches evaporate each week, calcium stays behind and concentrates around tile, spillways, dark finishes, and salt cells.", tags: ["calcium", "scale", "LSI"], facts: ["Many local hose bibs test at 250–450+ ppm calcium before the water enters the pool; repeated refill cycles can push a pool from 350 ppm to 800–1,200+ ppm.", "When pH rises above 7.6 and water heats up, a positive LSI above +0.30 lets calcium carbonate precipitate onto the easiest surfaces.", "Keep pH around 7.3–7.5 and total alkalinity near 70–80 ppm where appropriate. Sequestering agents can manage 500–800 ppm; mobile reverse osmosis is worth evaluating above 800–1,000 ppm.", "Skip pumice stones and raw acid on tile. Low-pressure kieserite or glass-bead media blasting can lift crust without etching the tile glaze."], takeaway: "Test the fill water before choosing a finish or treatment plan. Scale is a water-profile problem, not just a dirty tile problem." },
  { id: "salt-cell", number: "02", kicker: "Equipment care", title: "Salt cell maintenance: the real cost of neglect", intro: "A salt pool still needs inspection. In hard water, heat and high pH inside the electrolytic cell can plate calcium directly onto the titanium plates and turn a reliable chlorinator into an $800–$1,450 replacement.", tags: ["salt systems", "AquaRite", "IntelliChlor"], facts: ["Salt cells operate around 3,000–3,500 ppm salinity. Localized electrolysis can drive the cell’s internal pH above 9, accelerating scale bridges in 60–90 days of peak summer use.", "Scale restricts flow, creates false low-salt readings, and makes the control board work harder while chlorine production falls.", "Flush with a focused hose first. If an acid bath is needed, use a 4:1 water-to-muriatic-acid dilution, add acid to water, and stop when foaming subsides—never exceed 10–15 minutes.", "Never scrape between titanium plates with a screwdriver, putty knife, or wire brush. The ruthenium coating is thin and damage is permanent."], takeaway: "Quarterly cell service can preserve a five-to-seven-year operating life. A blinking inspect-cell warning is an equipment appointment, not a light to ignore." },
  { id: "storm", number: "03", kicker: "Weather response", title: "Santa Ana winds: the 48-hour recovery plan", intro: "A wind event brings more than leaves. Red clay silt carries phosphates, pollen, and organic load that can consume a pool’s free chlorine within 12 hours.", tags: ["Santa Ana", "silt", "storm"], facts: ["Hours 1–6: remove automatic cleaners, clear skimmer and pump baskets, restore water to halfway up the skimmer, and check pressure against the clean baseline.", "Hours 6–24: use fast-acting liquid chlorine to reach roughly 10–15 ppm free chlorine, add clarifier or enzyme where appropriate, and brush walls, steps, benches, and floor toward the drain.", "Hours 24–48: vacuum heavy silt to waste if plumbed. For cartridge filters, pull and wash every cartridge; silt cakes into pleats and ordinary running will not clear it.", "Do not vacuum palm fronds through a 1.5-inch suction line, let a pump cavitate on clogged baskets, or stack trichlor tabs to solve a storm load."], takeaway: "The first few hours protect the equipment pad. Debris removal, shock, and filter rebound work together; none is a substitute for the others." },
  { id: "phosphates", number: "04", kicker: "Sanitizer demand", title: "Why chlorine disappears overnight: the phosphate factor", intro: "When chlorine drops to zero even though the pool looks clear, invisible phosphate load may be feeding microscopic algae faster than your sanitizer can keep up.", tags: ["phosphates", "chlorine", "algae"], facts: ["Fertilizer drift, windblown soil, leaves, pollen, and some fill water introduce phosphate nutrients into the pool.", "At 500–1,000+ ppb, algae spores can reproduce continuously and consume chlorine before a visible bloom appears. Basic strips do not measure phosphate; use a specialized kit or photometer.", "Lanthanum-based remover binds phosphate into an insoluble precipitate that the filter captures. Temporary milky water is expected.", "Plan a complete filter breakdown and cleaning within 48–72 hours after treatment because the fine precipitate heavily loads grids or cartridges."], takeaway: "Repeated shock treats the symptom. Test phosphate when the water repeatedly loses sanitizer and look for the nutrient source." },
  { id: "filters", number: "05", kicker: "Filtration", title: "Cartridge, D.E., or sand: what a clean filter protects", intro: "The filter catches what chemistry cannot: dust, dead algae, body oils, and silt. A neglected filter raises backpressure, overheats pumps, and sends debris back into the pool.", tags: ["cartridge", "D.E.", "sand"], facts: ["Cartridge systems filter roughly 10–15 microns and need full disassembly, degreasing, and pleat-by-pleat washing every 3–6 months.", "D.E. systems can filter 2–5 microns, but require backwashing, fresh D.E. powder, and an annual grid inspection for tears.", "Sand filters generally capture 20–40 microns, need regular backwashing, and typically need media replacement every 4–5 years.", "Use the pressure gauge as your trigger: 8–10 PSI above the clean baseline means flow is restricted and service is due. Inspect the tank, O-rings, air relief, manifold, and seals—not just the outside of the cartridges."], takeaway: "Record the clean pressure after service. That one number makes filter care objective and can prevent pump motor burnout or crushed internal manifolds." },
  { id: "service", number: "06", kicker: "Service standards", title: "The true cost of splash-and-dash pool service", intro: "A four-minute basket empty and a few tabs is not a maintenance program. Water chemistry, the plaster surface, and the equipment pad all need a qualified eye.", tags: ["licensed care", "C-35", "service"], facts: ["Trichlor tablets have a pH near 2.8–3.0. Leaving them in a skimmer can send a concentrated acid slug through seals, impellers, and heater components when the pump restarts.", "Trichlor and dichlor continuously add cyanuric acid. Over time, CYA can reach 120–180+ ppm and make chlorine far less active.", "A complete visit considers pH, total alkalinity, calcium hardness, CYA, phosphates, LSI, salt cell condition, filter pressure, pump RPM, and early plaster or bond-beam warning signs.", "A licensed C-35 lathing and plastering contractor understands the shell, bond coat, curing cement matrix, and masonry movement—not only whether the water looks blue."], takeaway: "Ask what gets tested, what gets recorded, and how equipment is inspected. The cheapest visit can become the most expensive water-care plan." },
  { id: "black-algae", number: "07", kicker: "Algae remediation", title: "Black algae: why normal shock does not kill it", intro: "Black or dark-teal spots that resist brushing are often cyanobacteria rooted into plaster, quartz, or pebble. Its waxy sheath blocks ordinary chlorine while rhizoids anchor into the cement matrix.", tags: ["black algae", "plaster", "remediation"], facts: ["On traditional plaster, physical disruption with a stainless wire algae brush is the first step; pebble may need a compatible hybrid wire-poly brush.", "After opening the sheath, direct contact with a 3-inch trichlor tablet can deliver a localized high-chlorine treatment. Use chemical gloves and follow product safety instructions.", "Raise the pool to roughly 20–30 ppm free chlorine, consider a compatible copper or polyquat-60 algaecide, and brush twice daily for 5–7 days.", "If roots have reached old or hollow plaster and return every spring, surface treatment may not be durable. Drain, chip out infected finish, and replastering can be the restorative path."], takeaway: "A clear pool is not proof the organism is gone. Treat the root system and assess the condition of the finish before repeating shock." },
  { id: "pump", number: "08", kicker: "Energy & circulation", title: "Variable-speed pump schedules for triple-digit summers", intro: "Riverside pools need circulation through 88–92°F water, but peak utility hours are expensive. A variable-speed schedule can keep turnover moving while avoiding full-speed operation all day.", tags: ["variable speed", "RPM", "SCE"], facts: ["The pump affinity law is cubic: cut speed from 3,400 to 1,700 RPM and theoretical power drops by about 87.5%, while flow drops by half.", "A practical starting schedule is 2,600–2,800 RPM from 8 AM–2 PM for skimming and salt-cell flow, 2,000–2,200 RPM from 2–4 PM, 1,200–1,400 RPM from 4–9 PM, and 1,500–1,700 RPM from 9 PM–midnight.", "Confirm minimum flow for every component: salt cells often need roughly 25–35 GPM, heaters commonly need 30–40 GPM, and water features may need 2,400+ RPM.", "The correct RPM depends on pipe diameter, filter pressure, plumbing friction, heater flow, and the actual turnover target—not the motor’s horsepower label."], takeaway: "Have the schedule coordinated with the filter, heater, salt cell, and automation. Efficiency is a hydraulic system result." },
  { id: "washes", number: "09", kicker: "Restorative cleaning", title: "Acid wash vs. chlorine wash: which stained pool needs what?", intro: "A restorative wash can refresh a dull finish, but the wrong chemistry can shorten its life. The stain profile and plaster condition determine the safe method.", tags: ["acid wash", "chlorine wash", "stains"], facts: ["Acid wash micro-strips cement and exposes clean aggregate. It targets calcium scale, rust, iron, copper discoloration, and mineral haze, but repeated use removes finish thickness.", "Chlorine wash uses concentrated sodium hypochlorite to oxidize algae, leaf tannins, green slime, and organic bacteria without etching the cement matrix.", "Older plaster—roughly 10–15+ years old—plus hollow sounds, exposed aggregate, or thin finish makes acid washing higher risk and can turn a cleaning into replastering.", "Draining requires hydrostatic relief planning; dry heat can dehydrate plaster, and concentrated acid or chlorine fumes require proper respiratory protection and disposal."], takeaway: "Do not choose a wash by color alone. Evaluate finish age, thickness, hollow areas, water-table risk, and whether the stain is mineral or organic." },
  { id: "cya", number: "10", kicker: "Water reset", title: "Cyanuric acid lock: the silent cause of cloudy water", intro: "CYA protects chlorine from UV, but it does not evaporate. Repeated trichlor or dichlor use can push stabilizer high enough that chlorine reads present while too little remains active to sanitize.", tags: ["CYA", "cloudy water", "stabilizer"], facts: ["A useful operating window is approximately 30–50 ppm CYA for traditional chlorine pools and 60–80 ppm for many saltwater pools.", "At 100–150 ppm, the required free chlorine rises sharply. A practical rule is minimum free chlorine near 7.5% of CYA; at 150 ppm, that is about 11.25 ppm.", "There is no dependable additive that removes high CYA. Partial drain-and-refill is common, while mobile reverse osmosis can reduce CYA, calcium, and TDS without a full drain.", "Never drain a concrete pool during peak summer heat or elevated water-table conditions without professional supervision; hydrostatic pressure and plaster stress are real risks."], takeaway: "If high chlorine still leaves haze, stop adding shock blindly. Test CYA accurately and choose a supervised dilution or RO strategy." },
];

export function PoolCleaningCenter() {
  const [menu, setMenu] = useState(false);
  const [query, setQuery] = useState("");
  const [active, setActive] = useState<string | null>("hard-water");
  useEffect(() => {
    document.title = "Pool Cleaning & Maintenance Knowledge Center | Rivera Pools";
    document.querySelector('meta[name="description"]')?.setAttribute("content", "Ten practical pool cleaning and maintenance guides for Riverside County homeowners, covering chemistry, filtration, equipment, algae, weather, and restorative cleaning.");
  }, []);
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return topics.filter((topic) => !needle || `${topic.title} ${topic.kicker} ${topic.intro} ${topic.tags.join(" ")} ${topic.facts.join(" ")}`.toLowerCase().includes(needle));
  }, [query]);
  return (
    <div className="min-h-screen bg-[#f2f8f8] font-['DM_Sans',sans-serif] text-[#17324d]">
      <header className="sticky top-0 z-40 border-b border-[#d7e7e6] bg-[#f9fdfc]/95 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
          <a href="/" className="flex items-center gap-2" aria-label="Rivera Pools Riverside home"><Droplets className="h-8 w-8 text-[#0aa9ad]" /><span className="font-['Montserrat'] text-lg font-extrabold leading-none tracking-tight">RIVERA POOLS<span className="block text-[10px] font-semibold tracking-[.28em] text-[#607b83]">RIVERSIDE</span></span></a>
          <nav className="hidden items-center gap-7 md:flex"><a href="/blog" className="text-sm font-bold text-[#0a9298]">Knowledge center</a><a href="/blog/pool-remodeling" className="text-sm font-semibold text-[#607b83] hover:text-[#0a9298]">Remodeling library</a><a href="/#services" className="text-sm font-semibold text-[#607b83] hover:text-[#0a9298]">Services</a><a href="tel:+19513459276" className="flex items-center gap-2 text-sm font-bold"><Phone className="h-4 w-4 text-[#0aa9ad]" />(951) 345-9276</a></nav>
          <button className="rounded-lg p-2 md:hidden" onClick={() => setMenu(!menu)} aria-label={menu ? "Close menu" : "Open menu"}>{menu ? <X /> : <Menu />}</button>
        </div>
        {menu && <div className="border-t border-[#d7e7e6] bg-white p-4 md:hidden"><a href="/blog" className="block rounded-lg bg-[#e1f6f4] px-4 py-3 font-bold text-[#087b80]">Knowledge center</a><a href="/blog/pool-remodeling" className="mt-2 block rounded-lg px-4 py-3 font-semibold">Remodeling library</a><a href="tel:+19513459276" className="mt-2 block rounded-lg bg-[#0aa9ad] px-4 py-3 text-center font-bold text-white">Call (951) 345-9276</a></div>}
      </header>
      <main>
        <section className="relative overflow-hidden bg-[#123b52] px-5 py-16 text-white lg:px-8 lg:py-24">
          <div className="absolute -right-24 -top-28 h-96 w-96 rounded-full border-[38px] border-[#51d3c6]/15" /><div className="absolute bottom-[-6rem] left-[42%] h-64 w-64 rounded-full border border-[#51d3c6]/20" />
          <div className="relative mx-auto max-w-7xl"><div className="flex flex-wrap items-center gap-3 text-xs font-bold uppercase tracking-[.18em] text-[#8ae8dc]"><a href="/blog" className="hover:text-white">Field notes</a><span>/</span><span>Water care center</span></div><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_330px] lg:items-end"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#73e3d5]/30 bg-[#73e3d5]/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#a9f3e8]"><Waves className="h-3.5 w-3.5" /> Riverside pool care, decoded</div><h1 className="max-w-4xl font-['Montserrat'] text-4xl font-extrabold leading-[1.07] md:text-6xl">Clear water is a system, not a coincidence.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75">Ten practical guides for the heat, hard water, wind, dust, and equipment realities of Riverside County. Know what to test, what to clean, and when a warning deserves a professional look.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-[#8ae8dc]" /><span className="text-sm font-bold">10 topics · about 22 minutes</span></div><p className="mt-3 text-sm leading-relaxed text-white/65">Chemistry, filtration, equipment care, algae, weather recovery, and restorative cleaning—written for homeowners.</p></div></div></div>
        </section>
        <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="grid gap-10 lg:grid-cols-[245px_1fr]">
          <aside className="hidden lg:block"><div className="sticky top-28"><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#68828a]">In this guide</p><nav className="space-y-1">{topics.map((topic) => <a href={`#${topic.id}`} key={topic.id} className="flex gap-3 rounded-lg px-3 py-2 text-sm text-[#607b83] transition hover:bg-white hover:text-[#087b80]"><span className="font-['Space_Mono'] text-[10px] text-[#0aa9ad]">{topic.number}</span><span>{topic.title}</span></a>)}</nav><div className="mt-8 rounded-2xl bg-[#123b52] p-5 text-white"><ShieldCheck className="mb-4 h-6 w-6 text-[#8ae8dc]" /><p className="text-sm font-bold">Not sure what your water is telling you?</p><a href="/#contact" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#8ae8dc]">Book a water check <ArrowRight className="h-4 w-4" /></a></div></div></aside>
          <div><div className="mb-8 flex flex-col gap-4 border-b border-[#d7e7e6] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0a9298]">The care library</p><h2 className="mt-2 font-['Montserrat'] text-2xl font-extrabold md:text-3xl">Ten answers for the pool you have today.</h2><p className="mt-2 max-w-xl text-sm text-[#607b83]">Open a topic for field-tested details and a Rivera Pools takeaway.</p></div><label className="relative block sm:w-72"><Search className="absolute left-3 top-3 h-4 w-4 text-[#78949a]" /><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search chemistry, algae..." className="w-full rounded-xl border border-[#c9dfde] bg-white py-2.5 pl-9 pr-3 text-sm outline-none transition focus:border-[#0aa9ad] focus:ring-2 focus:ring-[#0aa9ad]/15" /></label></div>
            <div className="mb-7 flex gap-2 overflow-x-auto pb-1 lg:hidden">{topics.map((topic) => <a href={`#${topic.id}`} key={topic.id} className="shrink-0 rounded-full border border-[#c9dfde] bg-white px-3 py-2 text-xs font-bold text-[#47727b]">{topic.number} {topic.kicker}</a>)}</div>
            <div className="space-y-4">{filtered.map((topic) => <article id={topic.id} key={topic.id} className="scroll-mt-28 overflow-hidden rounded-2xl border border-[#d7e7e6] bg-white shadow-sm transition hover:shadow-md"><button onClick={() => setActive(active === topic.id ? null : topic.id)} className="flex w-full items-start gap-4 p-5 text-left md:p-7" aria-expanded={active === topic.id}><span className="font-['Space_Mono'] text-sm font-bold text-[#0aa9ad]">{topic.number}</span><span className="flex-1"><span className="block text-xs font-bold uppercase tracking-[.17em] text-[#0a9298]">{topic.kicker}</span><span className="mt-2 block font-['Montserrat'] text-xl font-extrabold leading-tight md:text-2xl">{topic.title}</span><span className="mt-3 block max-w-3xl leading-relaxed text-[#607b83]">{topic.intro}</span><span className="mt-4 flex flex-wrap gap-2">{topic.tags.map((tag) => <span key={tag} className="rounded-full bg-[#edf8f7] px-2.5 py-1 text-[11px] font-bold text-[#397d80]">#{tag}</span>)}</span></span><ChevronDown className={`mt-1 h-5 w-5 shrink-0 text-[#78949a] transition ${active === topic.id ? "rotate-180" : ""}`} /></button>{active === topic.id && <div className="border-t border-[#e4efee] bg-[#f8fcfb] px-5 pb-7 pt-6 md:px-[4.6rem]"><ul className="space-y-4">{topic.facts.map((fact) => <li key={fact} className="flex gap-3 text-[15px] leading-relaxed text-[#385b68]"><Check className="mt-1 h-4 w-4 shrink-0 text-[#0aa9ad]" />{fact}</li>)}</ul><div className="mt-6 flex gap-3 rounded-xl border-l-4 border-[#d3a62d] bg-[#fffaf0] p-4 text-sm leading-relaxed text-[#5c5033]"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#c29118]" /><span><strong className="font-bold">Rivera Pools takeaway:</strong> {topic.takeaway}</span></div></div>}</article>)}</div>{filtered.length === 0 && <div className="rounded-2xl border border-dashed border-[#b8d0ce] bg-white p-12 text-center"><Filter className="mx-auto h-7 w-7 text-[#0aa9ad]" /><p className="mt-3 font-['Montserrat'] font-bold">No matching topics</p><button onClick={() => setQuery("")} className="mt-3 text-sm font-bold text-[#087b80]">Clear search</button></div>}</div>
        </div></div>
      </main>
      <section className="bg-[#dff5f1] px-5 py-14 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0a9298]">Good maintenance catches patterns</p><h2 className="mt-2 font-['Montserrat'] text-2xl font-extrabold">Bring the warning sign to the site visit.</h2><p className="mt-2 max-w-xl text-[#526f78]">Rivera Pools can test the water, inspect the equipment, and explain whether you need routine care, a restoration, or a larger repair.</p></div><a href="/#contact" className="inline-flex items-center gap-2 rounded-xl bg-[#0aa9ad] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#0aa9ad]/20 transition hover:-translate-y-0.5 hover:bg-[#087b80]">Request a water assessment <ArrowRight className="h-4 w-4" /></a></div></section>
      <footer className="bg-[#102f43] px-5 py-8 text-center text-sm text-white/65"><p>Rivera Pools Riverside · Pool care, remodeling, resurfacing, and repairs across Riverside County.</p><p className="mt-2">CA C-35 Contractor License #1053279 · Licensed, Bonded, &amp; Insured</p><a href="tel:+19513459276" className="mt-2 inline-block font-bold text-[#8ae8dc]">(951) 345-9276</a></footer>
    </div>
  );
}