// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rivera-pools/BlogHub.tsx": () => import("../components/mockups/rivera-pools/BlogHub.tsx"),
  "./components/mockups/rivera-pools/BlogPost.tsx": () => import("../components/mockups/rivera-pools/BlogPost.tsx"),
  "./components/mockups/rivera-pools/ChatWidget.tsx": () => import("../components/mockups/rivera-pools/ChatWidget.tsx"),
  "./components/mockups/rivera-pools/CityLanding.tsx": () => import("../components/mockups/rivera-pools/CityLanding.tsx"),
  "./components/mockups/rivera-pools/Landing.tsx": () => import("../components/mockups/rivera-pools/Landing.tsx"),
  "./components/mockups/rivera-pools/PebbleVsQuartzPost.tsx": () => import("../components/mockups/rivera-pools/PebbleVsQuartzPost.tsx"),
  "./components/mockups/rivera-pools/PoolCleaningCenter.tsx": () => import("../components/mockups/rivera-pools/PoolCleaningCenter.tsx"),
  "./components/mockups/rivera-pools/PoolRemodelingCenter.tsx": () => import("../components/mockups/rivera-pools/PoolRemodelingCenter.tsx"),
  "./components/mockups/rivera-pools/QuoteForm.tsx": () => import("../components/mockups/rivera-pools/QuoteForm.tsx"),
  "./components/mockups/rivera-pools/ReviewModal.tsx": () => import("../components/mockups/rivera-pools/ReviewModal.tsx"),
  "./components/mockups/rivera-pools/ReviewPage.tsx": () => import("../components/mockups/rivera-pools/ReviewPage.tsx"),
  "./components/mockups/rivera-pools/SeoLanding.tsx": () => import("../components/mockups/rivera-pools/SeoLanding.tsx")
};
